# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  imageName: 'tsarspb/sandkasten'
  dockerHub: 'DockerHub'

stages:
- stage: BuildPushImage
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
    - job: BuildPushImage
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          containerRegistry: |
            $(dockerHub)
          repository: $(imageName)
          command: build
          Dockerfile: ./Dockerfile
          tags: |
            latest
            azPipe
      - task: Docker@2
        displayName: Push image
        inputs:
          containerRegistry: |
            $(dockerHub)
          repository: $(imageName)
          command: push
          tags: |
            latest
            azPipe
      - bash: |
          version=$(cat index.html)
          echo Printing logs....
          echo "##vso[task.setvariable variable=version]$version"