name: CDtest
on: 
  - push
      branches:
        - master
      tags:
        - 'release/**'
  - create:
      branches:
        - master
      tags:
        - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo Running $GITHUB_WORKFLOW on commit $GITHUB_SHA
